"""
sign_data.py
============
Single source of truth — รายการคำภาษามือทั้งหมด 327 คำ
Import ไฟล์นี้จาก app.py และ nlp_pipeline.py

โครงสร้างแต่ละ entry:
  thai   : คำภาษาไทย (key)
  emoji  : emoji แทนท่ามือ (ใช้แสดงเมื่อยังไม่มีคลิป)
  color  : สีประจำหมวด (hex)
  video  : ชื่อไฟล์ .mp4 ที่ต้องวางไว้ใน signs/
  category: หมวดหมู่
"""

# ─── Color per category ────────────────────────────────────────────────────────
CAT_COLOR = {
    "วันเวลา":       "#4472C4",
    "สถานที่":       "#70AD47",
    "กิริยา":        "#ED7D31",
    "อาการ":         "#C00000",
    "ยา":            "#9E480E",
    "คำสั่ง":        "#843C0C",
    "บุคลากร":       "#0070C0",
    "การตรวจ":       "#7030A0",
    "ความถี่ยา":     "#375623",
    "ปริมาณ":        "#833C00",
    "ร่างกาย":       "#C55A11",
    "อารมณ์":        "#2F75B6",
    "ฉุกเฉิน":       "#FF0000",
    "ตัวเลข":        "#1D6FA4",
}

# ─── NLP Simplification Rules ─────────────────────────────────────────────────
# (regex_pattern, replacement) — ลำดับมีความสำคัญ
SIMPLIFICATION_RULES = [
    # polite openers
    (r"กรุณา\s*", ""), (r"โปรด\s*", ""), (r"ขอให้\s*", ""), (r"ท่าน\s*", ""),
    # medical verb phrases
    (r"งดอาหาร", "ไม่กิน"), (r"งดน้ำ", "ไม่ดื่มน้ำ"),
    (r"รับประทาน", "กิน"), (r"บริโภค", "กิน"),
    (r"เข้ารับการตรวจ", "ตรวจ"), (r"เข้ารับการรักษา", "รักษา"),
    (r"รับการผ่าตัด", "ผ่าตัด"), (r"ปฏิบัติตาม", "ทำตาม"),
    (r"นอนพักผ่อน", "นอน"), (r"พักผ่อน", "พัก"),
    (r"ออกกำลังกาย", "เดิน"), (r"สอบถาม", "ถาม"),
    (r"แจ้งให้ทราบ", "บอก"), (r"แจ้งเจ้าหน้าที่", "บอกพยาบาล"),
    # people
    (r"แพทย์", "หมอ"), (r"เจ้าหน้าที่พยาบาล", "พยาบาล"),
    # substances
    (r"ยาเม็ด", "ยา"), (r"สารน้ำ", "น้ำ"),
    # temporal
    (r"ก่อนเข้ารับ", "ก่อน"), (r"หลังเข้ารับ", "หลัง"),
    (r"หลังการ", "หลัง"), (r"ก่อนการ", "ก่อน"),
    # dosage patterns — ลบ "ต่อวัน" ออกเพราะตัด token ไม่ได้ดี ใช้ "ทุกวัน" แทน
    (r"วันละ\s*(\d+)\s*ครั้ง", r"\1 ครั้ง ทุกวัน"),
    (r"ครั้งละ\s*(\d+)\s*เม็ด", r"\1 เม็ด"),
    (r"ทุก\s*(\d+)\s*ชั่วโมง", r"ทุก \1 ชม."),
    (r"ประมาณ\s*(\d+)\s*ชั่วโมง", r"\1 ชม."),
    # ── ตัดคำขยายที่ไม่จำเป็นออก ────────────────────────────────────────────
    (r"\d+\s*วันแล้ว", ""),   # "3 วันแล้ว" → ""
    (r"แล้ว\s*", ""),
    (r"จะ\s*", ""),
    (r"ใน\s*ตอน", ""),
    (r"ตอน\s*", ""),
    # symptoms
    (r"มีอาการปวด", "ปวด"), (r"มีอาการ", "มี"),
    (r"รู้สึก", ""),
    # ── ตัวเลขและช่อง ────────────────────────────────────────────────────────
    (r"ก่อนอาหาร\s*(\d+)\s*นาที", r"ก่อนอาหาร \1 นาที"),
    (r"หลังอาหาร\s*(\d+)\s*นาที", r"หลังอาหาร \1 นาที"),
    (r"ห้อง\s*เบอร์\s*(\d+)", r"ห้อง \1"),
    (r"ช่อง\s*เบอร์\s*(\d+)", r"ช่อง \1"),
    (r"หมายเลข\s*(\d+)", r"\1"),
    (r"เลขที่\s*(\d+)", r"\1"),
    # ── คำเชื่อมที่ไม่จำเป็น ──────────────────────────────────────────────────
    (r"ที่", ""), (r"ของ", ""), (r"คือ", ""),
    (r"ให้ท่านไป", "ไป"), (r"ท่านสามารถ", ""),
    (r"กรุณาไปที่", "ไป"), (r"กรุณาไป", "ไป"),
    # ── การเงินและการรับบริการ ────────────────────────────────────────────────
    (r"ชำระเงิน", "จ่ายเงิน"), (r"ชำระค่า", "จ่ายเงิน"),
    (r"รับยา", "รับ ยา"), (r"รับเอกสาร", "รับ เอกสาร"),
    (r"รับบัตร", "รับ บัตร"),
    (r"รอรับ", "รอ รับ"),
]

# ─── Master Sign Dictionary ────────────────────────────────────────────────────
# Format: "คำไทย": {"emoji","color","video","category"}

SIGN_DICT = {

    # ══════════════════════════════════════════════════
    # วันเวลาและปีเดือน
    # ══════════════════════════════════════════════════
    "เช้า":             {"emoji":"🌄","color":CAT_COLOR["วันเวลา"],"video":"chao.mp4",           "category":"วันเวลา"},
    "กลางวัน":          {"emoji":"☀️","color":CAT_COLOR["วันเวลา"],"video":"klang_wan.mp4",       "category":"วันเวลา"},
    "เย็น":             {"emoji":"🌇","color":CAT_COLOR["วันเวลา"],"video":"yen.mp4",             "category":"วันเวลา"},
    "คืน":              {"emoji":"🌙","color":CAT_COLOR["วันเวลา"],"video":"kuen.mp4",            "category":"วันเวลา"},
    "เที่ยงคืน":        {"emoji":"🕛","color":CAT_COLOR["วันเวลา"],"video":"thiang_kuen.mp4",     "category":"วันเวลา"},
    "วันนี้":           {"emoji":"📅","color":CAT_COLOR["วันเวลา"],"video":"wan_ni.mp4",          "category":"วันเวลา"},
    "เมื่อวาน":         {"emoji":"◀️","color":CAT_COLOR["วันเวลา"],"video":"muea_wan.mp4",        "category":"วันเวลา"},
    "พรุ่งนี้":         {"emoji":"🌅","color":CAT_COLOR["วันเวลา"],"video":"prung_ni.mp4",        "category":"วันเวลา"},
    "มะรืน":            {"emoji":"⏭️","color":CAT_COLOR["วันเวลา"],"video":"ma_ruen.mp4",         "category":"วันเวลา"},
    "อาทิตย์นี้":       {"emoji":"📆","color":CAT_COLOR["วันเวลา"],"video":"arthit_ni.mp4",       "category":"วันเวลา"},
    "เดือนนี้":         {"emoji":"🗓️","color":CAT_COLOR["วันเวลา"],"video":"duean_ni.mp4",        "category":"วันเวลา"},
    "ปีนี้":            {"emoji":"📅","color":CAT_COLOR["วันเวลา"],"video":"pi_ni.mp4",           "category":"วันเวลา"},
    "ปีที่แล้ว":        {"emoji":"⏮️","color":CAT_COLOR["วันเวลา"],"video":"pi_thi_laeo.mp4",     "category":"วันเวลา"},
    "ปีหน้า":           {"emoji":"⏩","color":CAT_COLOR["วันเวลา"],"video":"pi_na.mp4",           "category":"วันเวลา"},
    "จันทร์":           {"emoji":"1️⃣","color":CAT_COLOR["วันเวลา"],"video":"jan.mp4",             "category":"วันเวลา"},
    "อังคาร":           {"emoji":"2️⃣","color":CAT_COLOR["วันเวลา"],"video":"angkhan.mp4",         "category":"วันเวลา"},
    "พุธ":              {"emoji":"3️⃣","color":CAT_COLOR["วันเวลา"],"video":"phut.mp4",            "category":"วันเวลา"},
    "พฤหัส":            {"emoji":"4️⃣","color":CAT_COLOR["วันเวลา"],"video":"pharuehat.mp4",       "category":"วันเวลา"},
    "ศุกร์":            {"emoji":"5️⃣","color":CAT_COLOR["วันเวลา"],"video":"suk.mp4",             "category":"วันเวลา"},
    "เสาร์":            {"emoji":"6️⃣","color":CAT_COLOR["วันเวลา"],"video":"sao.mp4",             "category":"วันเวลา"},
    "อาทิตย์":          {"emoji":"7️⃣","color":CAT_COLOR["วันเวลา"],"video":"arthit.mp4",          "category":"วันเวลา"},
    "มกราคม":           {"emoji":"📆","color":CAT_COLOR["วันเวลา"],"video":"makara.mp4",           "category":"วันเวลา"},
    "กุมภาพันธ์":       {"emoji":"📆","color":CAT_COLOR["วันเวลา"],"video":"kumpha.mp4",           "category":"วันเวลา"},
    "มีนาคม":           {"emoji":"📆","color":CAT_COLOR["วันเวลา"],"video":"mina.mp4",             "category":"วันเวลา"},
    "เมษายน":           {"emoji":"📆","color":CAT_COLOR["วันเวลา"],"video":"mesha.mp4",            "category":"วันเวลา"},
    "พฤษภาคม":          {"emoji":"📆","color":CAT_COLOR["วันเวลา"],"video":"phruetsapha.mp4",      "category":"วันเวลา"},
    "มิถุนายน":         {"emoji":"📆","color":CAT_COLOR["วันเวลา"],"video":"mithuna.mp4",          "category":"วันเวลา"},
    "กรกฎาคม":          {"emoji":"📆","color":CAT_COLOR["วันเวลา"],"video":"karakada.mp4",         "category":"วันเวลา"},
    "สิงหาคม":          {"emoji":"📆","color":CAT_COLOR["วันเวลา"],"video":"singha.mp4",           "category":"วันเวลา"},
    "กันยายน":          {"emoji":"📆","color":CAT_COLOR["วันเวลา"],"video":"kanya.mp4",            "category":"วันเวลา"},
    "ตุลาคม":           {"emoji":"📆","color":CAT_COLOR["วันเวลา"],"video":"tula.mp4",             "category":"วันเวลา"},
    "พฤศจิกายน":        {"emoji":"📆","color":CAT_COLOR["วันเวลา"],"video":"phruetsajika.mp4",     "category":"วันเวลา"},
    "ธันวาคม":          {"emoji":"📆","color":CAT_COLOR["วันเวลา"],"video":"thanwa.mp4",           "category":"วันเวลา"},
    "นาที":             {"emoji":"⏱️","color":CAT_COLOR["วันเวลา"],"video":"nathi.mp4",            "category":"วันเวลา"},
    "ชั่วโมง":          {"emoji":"🕐","color":CAT_COLOR["วันเวลา"],"video":"chua_mong.mp4",        "category":"วันเวลา"},
    "ชม.":          {"emoji":"🕐","color":CAT_COLOR["วันเวลา"],"video":"chua_mong2.mp4",        "category":"วันเวลา"},
    "สัปดาห์":          {"emoji":"📅","color":CAT_COLOR["วันเวลา"],"video":"sapda.mp4",            "category":"วันเวลา"},
    "เดือน":            {"emoji":"🌑","color":CAT_COLOR["วันเวลา"],"video":"duean.mp4",            "category":"วันเวลา"},
    "ปี":               {"emoji":"📅","color":CAT_COLOR["วันเวลา"],"video":"pi.mp4",               "category":"วันเวลา"},
    "ตอนนี้":           {"emoji":"👆","color":CAT_COLOR["วันเวลา"],"video":"ton_ni.mp4",           "category":"วันเวลา"},
    "เร็วๆนี้":         {"emoji":"⚡","color":CAT_COLOR["วันเวลา"],"video":"reo_reo_ni.mp4",       "category":"วันเวลา"},
    "วันที่":         {"emoji":"⚡","color":CAT_COLOR["วันเวลา"],"video":"wanti.mp4",       "category":"วันเวลา"},

    # ══════════════════════════════════════════════════
    # สถานที่
    # ══════════════════════════════════════════════════
    "โรงพยาบาล":        {"emoji":"🏥","color":CAT_COLOR["สถานที่"],"video":"rong_payaban.mp4",     "category":"สถานที่"},
    "ห้องฉุกเฉิน":      {"emoji":"🚨","color":CAT_COLOR["สถานที่"],"video":"hong_chuk_choen.mp4",  "category":"สถานที่"},
    "ห้องตรวจ":         {"emoji":"🔬","color":CAT_COLOR["สถานที่"],"video":"hong_truat.mp4",       "category":"สถานที่"},
    "ห้องผ่าตัด":       {"emoji":"🔪","color":CAT_COLOR["สถานที่"],"video":"hong_pha_tat.mp4",     "category":"สถานที่"},
    "ห้องพักฟื้น":      {"emoji":"🛏️","color":CAT_COLOR["สถานที่"],"video":"hong_phak_fuen.mp4",   "category":"สถานที่"},
    "ห้องผู้ป่วย":      {"emoji":"🏠","color":CAT_COLOR["สถานที่"],"video":"hong_phu_puai.mp4",    "category":"สถานที่"},
    "ห้องน้ำ":          {"emoji":"🚻","color":CAT_COLOR["สถานที่"],"video":"hong_nam.mp4",         "category":"สถานที่"},
    "ห้องรับรอง":       {"emoji":"🪑","color":CAT_COLOR["สถานที่"],"video":"hong_rap_rong.mp4",    "category":"สถานที่"},
    "ลิฟต์":            {"emoji":"🛗","color":CAT_COLOR["สถานที่"],"video":"lift.mp4",             "category":"สถานที่"},
    "ชั้น":             {"emoji":"🏢","color":CAT_COLOR["สถานที่"],"video":"chan.mp4",              "category":"สถานที่"},
    "ตึก":              {"emoji":"🏢","color":CAT_COLOR["สถานที่"],"video":"tuek.mp4",             "category":"สถานที่"},
    "ทางออก":           {"emoji":"🚪","color":CAT_COLOR["สถานที่"],"video":"thang_ok.mp4",         "category":"สถานที่"},
    "ทางเข้า":          {"emoji":"🚪","color":CAT_COLOR["สถานที่"],"video":"thang_khao.mp4",       "category":"สถานที่"},
    "ร้านขายยา":        {"emoji":"💊","color":CAT_COLOR["สถานที่"],"video":"ran_khai_ya.mp4",      "category":"สถานที่"},
    "ห้องแล็บ":         {"emoji":"🧪","color":CAT_COLOR["สถานที่"],"video":"hong_laep.mp4",        "category":"สถานที่"},
    "คลินิก":           {"emoji":"🏥","color":CAT_COLOR["สถานที่"],"video":"khlinik.mp4",          "category":"สถานที่"},
    "บ้าน":             {"emoji":"🏠","color":CAT_COLOR["สถานที่"],"video":"ban.mp4",              "category":"สถานที่"},

    # ══════════════════════════════════════════════════
    # กิริยาและการกระทำทั่วไป
    # ══════════════════════════════════════════════════
    "กิน":              {"emoji":"🍽️","color":CAT_COLOR["กิริยา"],"video":"gin.mp4",              "category":"กิริยา"},
    "ดื่ม":             {"emoji":"🥤","color":CAT_COLOR["กิริยา"],"video":"duem.mp4",             "category":"กิริยา"},
    "นอน":              {"emoji":"🛏️","color":CAT_COLOR["กิริยา"],"video":"non.mp4",              "category":"กิริยา"},
    "นั่ง":             {"emoji":"🪑","color":CAT_COLOR["กิริยา"],"video":"nang.mp4",             "category":"กิริยา"},
    "ยืน":              {"emoji":"🧍","color":CAT_COLOR["กิริยา"],"video":"yuen.mp4",             "category":"กิริยา"},
    "เดิน":             {"emoji":"🚶","color":CAT_COLOR["กิริยา"],"video":"doen.mp4",             "category":"กิริยา"},
    "วิ่ง":             {"emoji":"🏃","color":CAT_COLOR["กิริยา"],"video":"wing.mp4",             "category":"กิริยา"},
    "หยุด":             {"emoji":"✋","color":CAT_COLOR["กิริยา"],"video":"yut.mp4",              "category":"กิริยา"},
    "มา":               {"emoji":"👋","color":CAT_COLOR["กิริยา"],"video":"ma.mp4",               "category":"กิริยา"},
    "ไป":               {"emoji":"➡️","color":CAT_COLOR["กิริยา"],"video":"pai.mp4",              "category":"กิริยา"},
    "กลับ":             {"emoji":"↩️","color":CAT_COLOR["กิริยา"],"video":"klap.mp4",             "category":"กิริยา"},
    "ขึ้น":             {"emoji":"⬆️","color":CAT_COLOR["กิริยา"],"video":"khuen.mp4",            "category":"กิริยา"},
    "ลง":               {"emoji":"⬇️","color":CAT_COLOR["กิริยา"],"video":"long.mp4",             "category":"กิริยา"},
    "เปิด":             {"emoji":"🔓","color":CAT_COLOR["กิริยา"],"video":"poet.mp4",             "category":"กิริยา"},
    "ปิด":              {"emoji":"🔒","color":CAT_COLOR["กิริยา"],"video":"pit.mp4",              "category":"กิริยา"},
    "ใส่":              {"emoji":"👕","color":CAT_COLOR["กิริยา"],"video":"sai.mp4",              "category":"กิริยา"},
    "เอา":              {"emoji":"🤲","color":CAT_COLOR["กิริยา"],"video":"ao.mp4",               "category":"กิริยา"},
    "ให้":              {"emoji":"🎁","color":CAT_COLOR["กิริยา"],"video":"hai.mp4",              "category":"กิริยา"},
    "รับ":              {"emoji":"🤝","color":CAT_COLOR["กิริยา"],"video":"rap.mp4",              "category":"กิริยา"},
    "ถือ":              {"emoji":"✊","color":CAT_COLOR["กิริยา"],"video":"thue.mp4",             "category":"กิริยา"},
    "วาง":              {"emoji":"🖐️","color":CAT_COLOR["กิริยา"],"video":"wang.mp4",             "category":"กิริยา"},
    "เรียก":            {"emoji":"📣","color":CAT_COLOR["กิริยา"],"video":"riak.mp4",             "category":"กิริยา"},
    "บอก":              {"emoji":"🗣️","color":CAT_COLOR["กิริยา"],"video":"bok.mp4",              "category":"กิริยา"},
    "ถาม":              {"emoji":"❓","color":CAT_COLOR["กิริยา"],"video":"tham.mp4",             "category":"กิริยา"},
    "ตอบ":              {"emoji":"💬","color":CAT_COLOR["กิริยา"],"video":"top.mp4",              "category":"กิริยา"},
    "อ่าน":             {"emoji":"📖","color":CAT_COLOR["กิริยา"],"video":"an.mp4",               "category":"กิริยา"},
    "เขียน":            {"emoji":"✏️","color":CAT_COLOR["กิริยา"],"video":"khian.mp4",            "category":"กิริยา"},
    "ดู":               {"emoji":"👀","color":CAT_COLOR["กิริยา"],"video":"du.mp4",               "category":"กิริยา"},
    "ฟัง":              {"emoji":"👂","color":CAT_COLOR["กิริยา"],"video":"fang.mp4",             "category":"กิริยา"},
    "รอ":               {"emoji":"⏳","color":CAT_COLOR["กิริยา"],"video":"ro.mp4",               "category":"กิริยา"},
    "ช่วย":             {"emoji":"🤝","color":CAT_COLOR["กิริยา"],"video":"chuai.mp4",            "category":"กิริยา"},
    "ทำตาม":            {"emoji":"🙌","color":CAT_COLOR["กิริยา"],"video":"tham_tam.mp4",         "category":"กิริยา"},
    "เข้าใจ":           {"emoji":"💡","color":CAT_COLOR["กิริยา"],"video":"khao_jai.mp4",         "category":"กิริยา"},
    "ไม่เข้าใจ":        {"emoji":"😕","color":CAT_COLOR["กิริยา"],"video":"mai_khao_jai.mp4",     "category":"กิริยา"},
    "ลอง":              {"emoji":"🔄","color":CAT_COLOR["กิริยา"],"video":"long_try.mp4",         "category":"กิริยา"},

    # ══════════════════════════════════════════════════
    # อาการและความเจ็บปวด
    # ══════════════════════════════════════════════════
    "ปวด":              {"emoji":"🤕","color":CAT_COLOR["อาการ"],"video":"puat.mp4",              "category":"อาการ"},
    "เจ็บ":             {"emoji":"😣","color":CAT_COLOR["อาการ"],"video":"jeb.mp4",               "category":"อาการ"},
    "อักเสบ":             {"emoji":"😣","color":CAT_COLOR["อาการ"],"video":"seab.mp4",               "category":"อาการ"},
    "ปวดหัว":           {"emoji":"🤯","color":CAT_COLOR["อาการ"],"video":"puat_hua.mp4",          "category":"อาการ"},
    "ปวดท้อง":          {"emoji":"🤢","color":CAT_COLOR["อาการ"],"video":"puat_thong.mp4",        "category":"อาการ"},
    "ปวดหลัง":          {"emoji":"😖","color":CAT_COLOR["อาการ"],"video":"puat_lang.mp4",         "category":"อาการ"},
    "ปวดอก":            {"emoji":"💔","color":CAT_COLOR["อาการ"],"video":"puat_ok.mp4",           "category":"อาการ"},
    "ปวดข้อ":           {"emoji":"🦴","color":CAT_COLOR["อาการ"],"video":"puat_kho.mp4",          "category":"อาการ"},
    "ปวดกล้ามเนื้อ":    {"emoji":"💪","color":CAT_COLOR["อาการ"],"video":"puat_klam_nuea.mp4",    "category":"อาการ"},
    "คลื่นไส้":         {"emoji":"🤢","color":CAT_COLOR["อาการ"],"video":"khluean_sai.mp4",       "category":"อาการ"},
    "อาเจียน":          {"emoji":"🤮","color":CAT_COLOR["อาการ"],"video":"a_jian.mp4",            "category":"อาการ"},
    "เวียนหัว":         {"emoji":"😵","color":CAT_COLOR["อาการ"],"video":"wian_hua.mp4",          "category":"อาการ"},
    "หายใจลำบาก":       {"emoji":"😮‍💨","color":CAT_COLOR["อาการ"],"video":"hai_jai_lam_bak.mp4", "category":"อาการ"},
    "ไอ":               {"emoji":"😮","color":CAT_COLOR["อาการ"],"video":"ai.mp4",                "category":"อาการ"},
    "จาม":              {"emoji":"🤧","color":CAT_COLOR["อาการ"],"video":"jam.mp4",               "category":"อาการ"},
    "มีไข้":            {"emoji":"🌡️","color":CAT_COLOR["อาการ"],"video":"mi_khai.mp4",           "category":"อาการ"},
    "หนาวสั่น":         {"emoji":"🥶","color":CAT_COLOR["อาการ"],"video":"nao_san.mp4",           "category":"อาการ"},
    "อ่อนเพลีย":        {"emoji":"😴","color":CAT_COLOR["อาการ"],"video":"on_phlia.mp4",          "category":"อาการ"},
    "บวม":              {"emoji":"🫧","color":CAT_COLOR["อาการ"],"video":"buam.mp4",              "category":"อาการ"},
    "คัน":              {"emoji":"🤚","color":CAT_COLOR["อาการ"],"video":"khan.mp4",              "category":"อาการ"},
    "แสบ":              {"emoji":"🔥","color":CAT_COLOR["อาการ"],"video":"saep.mp4",              "category":"อาการ"},
    "ชา":               {"emoji":"😶","color":CAT_COLOR["อาการ"],"video":"cha_numb.mp4",          "category":"อาการ"},
    "อ่อนแรง":          {"emoji":"😩","color":CAT_COLOR["อาการ"],"video":"on_raeng.mp4",          "category":"อาการ"},
    "สั่น":             {"emoji":"〰️","color":CAT_COLOR["อาการ"],"video":"san.mp4",              "category":"อาการ"},
    "เป็นลม":           {"emoji":"😵","color":CAT_COLOR["อาการ"],"video":"pen_lom.mp4",           "category":"อาการ"},
    "ชัก":              {"emoji":"⚡","color":CAT_COLOR["อาการ"],"video":"chak.mp4",              "category":"อาการ"},
    "เลือดออก":         {"emoji":"🩸","color":CAT_COLOR["อาการ"],"video":"lueat_ok.mp4",          "category":"อาการ"},
    "หมดสติ":           {"emoji":"💫","color":CAT_COLOR["อาการ"],"video":"mot_sati.mp4",          "category":"อาการ"},
    "แพ้":              {"emoji":"🤧","color":CAT_COLOR["อาการ"],"video":"phae.mp4",              "category":"อาการ"},
    "แผล":              {"emoji":"🩹","color":CAT_COLOR["อาการ"],"video":"plae.mp4",              "category":"อาการ"},
    "รอยช้ำ":           {"emoji":"🟣","color":CAT_COLOR["อาการ"],"video":"roi_cham.mp4",          "category":"อาการ"},
    "กระดูกหัก":        {"emoji":"🦴","color":CAT_COLOR["อาการ"],"video":"kraduk_hak.mp4",        "category":"อาการ"},

    # ══════════════════════════════════════════════════
    # ยาและการรักษา
    # ══════════════════════════════════════════════════
    "ยา":               {"emoji":"💊","color":CAT_COLOR["ยา"],"video":"ya.mp4",                   "category":"ยา"},
    "ยาเม็ด":           {"emoji":"💊","color":CAT_COLOR["ยา"],"video":"ya_met.mp4",               "category":"ยา"},
    "ยาน้ำ":            {"emoji":"🧴","color":CAT_COLOR["ยา"],"video":"ya_nam.mp4",               "category":"ยา"},
    "ยาฉีด":            {"emoji":"💉","color":CAT_COLOR["ยา"],"video":"ya_cheet.mp4",             "category":"ยา"},
    "ยาพ่น":            {"emoji":"💨","color":CAT_COLOR["ยา"],"video":"ya_phen.mp4",              "category":"ยา"},
    "ยาทาแผล":           {"emoji":"🧴","color":CAT_COLOR["ยา"],"video":"ya_khrim.mp4",             "category":"ยา"},
    "ยาหยอดตา":         {"emoji":"👁️","color":CAT_COLOR["ยา"],"video":"ya_yot_ta.mp4",            "category":"ยา"},
    "วิตามิน":          {"emoji":"🌿","color":CAT_COLOR["ยา"],"video":"witamin.mp4",              "category":"ยา"},
    "ยาปฏิชีวนะ":       {"emoji":"🦠","color":CAT_COLOR["ยา"],"video":"ya_patichiwana.mp4",       "category":"ยา"},
    "ยาแก้ปวด":         {"emoji":"💊","color":CAT_COLOR["ยา"],"video":"ya_kae_puat.mp4",          "category":"ยา"},
    "ยาลดไข้":          {"emoji":"🌡️","color":CAT_COLOR["ยา"],"video":"ya_lot_khai.mp4",          "category":"ยา"},
    "น้ำเกลือ":         {"emoji":"💧","color":CAT_COLOR["ยา"],"video":"nam_kluea.mp4",            "category":"ยา"},
    "ฉีดยา":            {"emoji":"💉","color":CAT_COLOR["ยา"],"video":"cheet_ya.mp4",             "category":"ยา"},
    "ผ่าตัด":           {"emoji":"🔪","color":CAT_COLOR["ยา"],"video":"pha_tat.mp4",              "category":"ยา"},
    "ทำแผล":            {"emoji":"🩹","color":CAT_COLOR["ยา"],"video":"tham_plae.mp4",            "category":"ยา"},
    "เย็บแผล":          {"emoji":"🧵","color":CAT_COLOR["ยา"],"video":"yep_plae.mp4",             "category":"ยา"},
    "เฝือก":            {"emoji":"🦴","color":CAT_COLOR["ยา"],"video":"fueok.mp4",               "category":"ยา"},
    "ไม้ค้ำ":           {"emoji":"🦯","color":CAT_COLOR["ยา"],"video":"mai_kham.mp4",             "category":"ยา"},
    "รักษา":            {"emoji":"❤️‍🩹","color":CAT_COLOR["ยา"],"video":"raksa.mp4",               "category":"ยา"},
    "ถ่ายเลือด":        {"emoji":"🩸","color":CAT_COLOR["ยา"],"video":"thai_lueat.mp4",           "category":"ยา"},
    "ให้น้ำเกลือ":      {"emoji":"💉","color":CAT_COLOR["ยา"],"video":"hai_nam_kluea.mp4",        "category":"ยา"},
    "ล้างแผล":          {"emoji":"🚿","color":CAT_COLOR["ยา"],"video":"lang_plae.mp4",            "category":"ยา"},

    # ══════════════════════════════════════════════════
    # คำสั่งและการปฏิบัติ
    # ══════════════════════════════════════════════════
    "ไม่กิน":              {"emoji":"🚫","color":CAT_COLOR["คำสั่ง"],"video":"mai.mp4",              "category":"คำสั่ง"},
    "ไม่ได้":           {"emoji":"❌","color":CAT_COLOR["คำสั่ง"],"video":"mai_dai.mp4",          "category":"คำสั่ง"},
    "ห้าม":             {"emoji":"🛑","color":CAT_COLOR["คำสั่ง"],"video":"ham.mp4",              "category":"คำสั่ง"},
    "ต้อง":             {"emoji":"✅","color":CAT_COLOR["คำสั่ง"],"video":"tong.mp4",             "category":"คำสั่ง"},
    "ควร":              {"emoji":"👍","color":CAT_COLOR["คำสั่ง"],"video":"khuan.mp4",            "category":"คำสั่ง"},
    "ได้":              {"emoji":"✔️","color":CAT_COLOR["คำสั่ง"],"video":"dai.mp4",              "category":"คำสั่ง"},
    "หายใจ":            {"emoji":"💨","color":CAT_COLOR["คำสั่ง"],"video":"hai_jai.mp4",          "category":"คำสั่ง"},
    "หายใจเข้า":        {"emoji":"⬇️","color":CAT_COLOR["คำสั่ง"],"video":"hai_jai_khao.mp4",    "category":"คำสั่ง"},
    "หายใจออก":         {"emoji":"⬆️","color":CAT_COLOR["คำสั่ง"],"video":"hai_jai_ok.mp4",      "category":"คำสั่ง"},
    "กลืน":             {"emoji":"👄","color":CAT_COLOR["คำสั่ง"],"video":"kluen.mp4",            "category":"คำสั่ง"},
    "บ้วนปาก":          {"emoji":"💦","color":CAT_COLOR["คำสั่ง"],"video":"buan_pak.mp4",         "category":"คำสั่ง"},
    "ล้างมือ":          {"emoji":"🙌","color":CAT_COLOR["คำสั่ง"],"video":"lang_mue.mp4",         "category":"คำสั่ง"},
    "อาหาร":          {"emoji":"🚫","color":CAT_COLOR["คำสั่ง"],"video":"ahan.mp4",        "category":"คำสั่ง"},
    "งด":            {"emoji":"🚫","color":CAT_COLOR["คำสั่ง"],"video":"ngot.mp4",         "category":"คำสั่ง"},
    "พัก":              {"emoji":"😴","color":CAT_COLOR["คำสั่ง"],"video":"phak.mp4",             "category":"คำสั่ง"},
    "นอนหงาย":          {"emoji":"🛏️","color":CAT_COLOR["คำสั่ง"],"video":"non_ngai.mp4",         "category":"คำสั่ง"},
    "นอนตะแคง":         {"emoji":"🛏️","color":CAT_COLOR["คำสั่ง"],"video":"non_ta_khaeng.mp4",   "category":"คำสั่ง"},
    "คว่ำ":             {"emoji":"🛏️","color":CAT_COLOR["คำสั่ง"],"video":"khwam.mp4",            "category":"คำสั่ง"},
    "แขนซ้าย":          {"emoji":"🫲","color":CAT_COLOR["คำสั่ง"],"video":"khaen_sai.mp4",        "category":"คำสั่ง"},
    "แขนขวา":           {"emoji":"🫱","color":CAT_COLOR["คำสั่ง"],"video":"khaen_khwa.mp4",       "category":"คำสั่ง"},

    # ══════════════════════════════════════════════════
    # บุคลากรทางการแพทย์
    # ══════════════════════════════════════════════════
    "หมอ":              {"emoji":"👨‍⚕️","color":CAT_COLOR["บุคลากร"],"video":"mor.mp4",            "category":"บุคลากร"},
    "พยาบาล":           {"emoji":"👩‍⚕️","color":CAT_COLOR["บุคลากร"],"video":"payaban.mp4",        "category":"บุคลากร"},
    "เภสัชกร":          {"emoji":"💊","color":CAT_COLOR["บุคลากร"],"video":"phesatchakorn.mp4",    "category":"บุคลากร"},
    "นักกายภาพ":        {"emoji":"🦾","color":CAT_COLOR["บุคลากร"],"video":"nak_kaiyaphap.mp4",    "category":"บุคลากร"},
    "นักรังสี":         {"emoji":"☢️","color":CAT_COLOR["บุคลากร"],"video":"nak_rangsi.mp4",       "category":"บุคลากร"},
    "ทันตแพทย์":        {"emoji":"🦷","color":CAT_COLOR["บุคลากร"],"video":"thanta_phaet.mp4",     "category":"บุคลากร"},
    "จิตแพทย์":         {"emoji":"🧠","color":CAT_COLOR["บุคลากร"],"video":"jit_phaet.mp4",        "category":"บุคลากร"},
    "ศัลยแพทย์":        {"emoji":"🔪","color":CAT_COLOR["บุคลากร"],"video":"sanya_phaet.mp4",      "category":"บุคลากร"},
    "ผู้ป่วย":          {"emoji":"🤒","color":CAT_COLOR["บุคลากร"],"video":"phu_puai.mp4",         "category":"บุคลากร"},
    "ญาติ":             {"emoji":"👨‍👩‍👧","color":CAT_COLOR["บุคลากร"],"video":"yati.mp4",           "category":"บุคลากร"},
    "ล่าม":             {"emoji":"🤟","color":CAT_COLOR["บุคลากร"],"video":"lam.mp4",              "category":"บุคลากร"},
    "อาสาสมัคร":        {"emoji":"🙋","color":CAT_COLOR["บุคลากร"],"video":"asa_samak.mp4",        "category":"บุคลากร"},

    # ══════════════════════════════════════════════════
    # การตรวจและวินิจฉัย
    # ══════════════════════════════════════════════════
    "ตรวจ":             {"emoji":"🔬","color":CAT_COLOR["การตรวจ"],"video":"truat.mp4",            "category":"การตรวจ"},
    "วัด":             {"emoji":"🔬","color":CAT_COLOR["การตรวจ"],"video":"wat.mp4",            "category":"การตรวจ"},
    "เจาะเลือด":        {"emoji":"🩸","color":CAT_COLOR["การตรวจ"],"video":"jo_lueat.mp4",         "category":"การตรวจ"},
    "ตรวจปัสสาวะ":      {"emoji":"🧪","color":CAT_COLOR["การตรวจ"],"video":"truat_patxawa.mp4",    "category":"การตรวจ"},
    "ตรวจอุจจาระ":      {"emoji":"🧪","color":CAT_COLOR["การตรวจ"],"video":"truat_utjara.mp4",     "category":"การตรวจ"},
    "เอกซเรย์":         {"emoji":"🦴","color":CAT_COLOR["การตรวจ"],"video":"eksare.mp4",           "category":"การตรวจ"},
    "อัลตราซาวด์":      {"emoji":"🔊","color":CAT_COLOR["การตรวจ"],"video":"altra_sao.mp4",        "category":"การตรวจ"},
    "สแกน":             {"emoji":"📡","color":CAT_COLOR["การตรวจ"],"video":"skaen.mp4",            "category":"การตรวจ"},
    "MRI":              {"emoji":"🧲","color":CAT_COLOR["การตรวจ"],"video":"MRI.mp4",              "category":"การตรวจ"},
    "CT scan":          {"emoji":"💿","color":CAT_COLOR["การตรวจ"],"video":"CT_scan.mp4",          "category":"การตรวจ"},
    "ฟังเสียง":         {"emoji":"🩺","color":CAT_COLOR["การตรวจ"],"video":"fang_siang.mp4",       "category":"การตรวจ"},
    "ความดันโลหิตสูง":       {"emoji":"💉","color":CAT_COLOR["การตรวจ"],"video":"khwam_dan.mp4",    "category":"การตรวจ"},
    "วัดชีพจร":         {"emoji":"❤️","color":CAT_COLOR["การตรวจ"],"video":"wat_chip_jon.mp4",     "category":"การตรวจ"},
    "วัดไข้":           {"emoji":"🌡️","color":CAT_COLOR["การตรวจ"],"video":"wat_khai.mp4",         "category":"การตรวจ"},
    "ชั่งน้ำหนัก":      {"emoji":"⚖️","color":CAT_COLOR["การตรวจ"],"video":"chang_nam_nak.mp4",   "category":"การตรวจ"},
    "วัดส่วนสูง":       {"emoji":"📏","color":CAT_COLOR["การตรวจ"],"video":"wat_suan_sung.mp4",    "category":"การตรวจ"},
    "ตรวจตา":           {"emoji":"👁️","color":CAT_COLOR["การตรวจ"],"video":"truat_ta.mp4",         "category":"การตรวจ"},
    "ตรวจหู":           {"emoji":"👂","color":CAT_COLOR["การตรวจ"],"video":"truat_hu.mp4",         "category":"การตรวจ"},
    "ตรวจฟัน":          {"emoji":"🦷","color":CAT_COLOR["การตรวจ"],"video":"truat_fan.mp4",        "category":"การตรวจ"},
    "ตรวจหัวใจ":        {"emoji":"❤️","color":CAT_COLOR["การตรวจ"],"video":"truat_hua_jai.mp4",   "category":"การตรวจ"},
    "ผลการตรวจ":        {"emoji":"📋","color":CAT_COLOR["การตรวจ"],"video":"phon_truat.mp4",       "category":"การตรวจ"},
    "นัดหมาย":          {"emoji":"📅","color":CAT_COLOR["การตรวจ"],"video":"nat_mai.mp4",          "category":"การตรวจ"},

    # ══════════════════════════════════════════════════
    # เวลาและความถี่การใช้ยา
    # ══════════════════════════════════════════════════
    "ก่อน":             {"emoji":"⬅️","color":CAT_COLOR["ความถี่ยา"],"video":"kon.mp4",            "category":"ความถี่ยา"},
    "หลัง":             {"emoji":"➡️","color":CAT_COLOR["ความถี่ยา"],"video":"lang.mp4",           "category":"ความถี่ยา"},
    "ก่อนอาหาร":        {"emoji":"🍽️","color":CAT_COLOR["ความถี่ยา"],"video":"kon_ahan.mp4",       "category":"ความถี่ยา"},
    "หลังอาหาร":        {"emoji":"🍽️","color":CAT_COLOR["ความถี่ยา"],"video":"lang_ahan.mp4",      "category":"ความถี่ยา"},
    "พร้อมอาหาร":       {"emoji":"🍽️","color":CAT_COLOR["ความถี่ยา"],"video":"phrom_ahan.mp4",     "category":"ความถี่ยา"},
    "ก่อนนอน":          {"emoji":"🛏️","color":CAT_COLOR["ความถี่ยา"],"video":"kon_non.mp4",         "category":"ความถี่ยา"},
    "ทุกวัน":           {"emoji":"🔁","color":CAT_COLOR["ความถี่ยา"],"video":"thuk_wan.mp4",        "category":"ความถี่ยา"},
    "วันเว้นวัน":       {"emoji":"🔀","color":CAT_COLOR["ความถี่ยา"],"video":"wan_wen_wan.mp4",     "category":"ความถี่ยา"},
    "ทุกสัปดาห์":       {"emoji":"📅","color":CAT_COLOR["ความถี่ยา"],"video":"thuk_sapda.mp4",      "category":"ความถี่ยา"},
    "ครั้ง":            {"emoji":"🔢","color":CAT_COLOR["ความถี่ยา"],"video":"khrang.mp4",          "category":"ความถี่ยา"},
    "เม็ด":             {"emoji":"💊","color":CAT_COLOR["ความถี่ยา"],"video":"met.mp4",             "category":"ความถี่ยา"},
    "มื้อ":             {"emoji":"🍽️","color":CAT_COLOR["ความถี่ยา"],"video":"mue.mp4",             "category":"ความถี่ยา"},
    "เมื่อมีอาการ":     {"emoji":"⚠️","color":CAT_COLOR["ความถี่ยา"],"video":"muea_mi_akan.mp4",   "category":"ความถี่ยา"},
    "โมง":     {"emoji":"⚠️","color":CAT_COLOR["ความถี่ยา"],"video":"mong.mp4",   "category":"ความถี่ยา"},
    # ══════════════════════════════════════════════════
    # ปริมาณและระดับ
    # ══════════════════════════════════════════════════
    "มาก":              {"emoji":"⬆️","color":CAT_COLOR["ปริมาณ"],"video":"mak.mp4",              "category":"ปริมาณ"},
    "น้อย":             {"emoji":"🤏","color":CAT_COLOR["ปริมาณ"],"video":"noi.mp4",              "category":"ปริมาณ"},
    "ปานกลาง":          {"emoji":"➡️","color":CAT_COLOR["ปริมาณ"],"video":"pan_klang.mp4",        "category":"ปริมาณ"},
    "มากที่สุด":        {"emoji":"🔝","color":CAT_COLOR["ปริมาณ"],"video":"mak_thi_sut.mp4",      "category":"ปริมาณ"},
    "น้อยที่สุด":       {"emoji":"⬇️","color":CAT_COLOR["ปริมาณ"],"video":"noi_thi_sut.mp4",     "category":"ปริมาณ"},
    "เพิ่ม":            {"emoji":"➕","color":CAT_COLOR["ปริมาณ"],"video":"phoem.mp4",            "category":"ปริมาณ"},
    "ลด":               {"emoji":"➖","color":CAT_COLOR["ปริมาณ"],"video":"lot.mp4",              "category":"ปริมาณ"},
    "ทั้งหมด":          {"emoji":"💯","color":CAT_COLOR["ปริมาณ"],"video":"thang_mot.mp4",        "category":"ปริมาณ"},
    "ครึ่ง":            {"emoji":"½","color":CAT_COLOR["ปริมาณ"],"video":"khrueng.mp4",          "category":"ปริมาณ"},
    "หนึ่ง":            {"emoji":"1️⃣","color":CAT_COLOR["ปริมาณ"],"video":"nueng.mp4",            "category":"ปริมาณ"},
    "สอง":              {"emoji":"2️⃣","color":CAT_COLOR["ปริมาณ"],"video":"song.mp4",             "category":"ปริมาณ"},
    "สาม":              {"emoji":"3️⃣","color":CAT_COLOR["ปริมาณ"],"video":"sam.mp4",              "category":"ปริมาณ"},
    "สี่":              {"emoji":"4️⃣","color":CAT_COLOR["ปริมาณ"],"video":"si.mp4",               "category":"ปริมาณ"},
    "ห้า":              {"emoji":"5️⃣","color":CAT_COLOR["ปริมาณ"],"video":"ha.mp4",               "category":"ปริมาณ"},
    "หก":               {"emoji":"6️⃣","color":CAT_COLOR["ปริมาณ"],"video":"hok.mp4",              "category":"ปริมาณ"},
    "เจ็ด":             {"emoji":"7️⃣","color":CAT_COLOR["ปริมาณ"],"video":"jet.mp4",              "category":"ปริมาณ"},
    "แปด":              {"emoji":"8️⃣","color":CAT_COLOR["ปริมาณ"],"video":"paet.mp4",             "category":"ปริมาณ"},
    "เก้า":             {"emoji":"9️⃣","color":CAT_COLOR["ปริมาณ"],"video":"kao.mp4",              "category":"ปริมาณ"},
    "สิบ":              {"emoji":"🔟","color":CAT_COLOR["ปริมาณ"],"video":"sip.mp4",              "category":"ปริมาณ"},
    "เร็ว":             {"emoji":"⚡","color":CAT_COLOR["ปริมาณ"],"video":"reo.mp4",              "category":"ปริมาณ"},
    "ช้า":              {"emoji":"🐢","color":CAT_COLOR["ปริมาณ"],"video":"cha.mp4",              "category":"ปริมาณ"},
    "แรง":              {"emoji":"💪","color":CAT_COLOR["ปริมาณ"],"video":"raeng.mp4",            "category":"ปริมาณ"},
    "เบา":              {"emoji":"🪶","color":CAT_COLOR["ปริมาณ"],"video":"bao.mp4",              "category":"ปริมาณ"},

    # ══════════════════════════════════════════════════
    # ร่างกาย
    # ══════════════════════════════════════════════════
    "หัว":              {"emoji":"🗣️","color":CAT_COLOR["ร่างกาย"],"video":"hua.mp4",              "category":"ร่างกาย"},
    "ร่างกาย":              {"emoji":"🗣️","color":CAT_COLOR["ร่างกาย"],"video":"ranggai.mp4",              "category":"ร่างกาย"},
    "ใบหน้า":           {"emoji":"😊","color":CAT_COLOR["ร่างกาย"],"video":"bai_na.mp4",           "category":"ร่างกาย"},
    "ผม":               {"emoji":"💇","color":CAT_COLOR["ร่างกาย"],"video":"phom.mp4",             "category":"ร่างกาย"},
    "หน้าผาก":          {"emoji":"🧠","color":CAT_COLOR["ร่างกาย"],"video":"na_phak.mp4",          "category":"ร่างกาย"},
    "ตา":               {"emoji":"👁️","color":CAT_COLOR["ร่างกาย"],"video":"ta.mp4",               "category":"ร่างกาย"},
    "หู":               {"emoji":"👂","color":CAT_COLOR["ร่างกาย"],"video":"hu.mp4",               "category":"ร่างกาย"},
    "จมูก":             {"emoji":"👃","color":CAT_COLOR["ร่างกาย"],"video":"jamuk.mp4",            "category":"ร่างกาย"},
    "ปาก":              {"emoji":"👄","color":CAT_COLOR["ร่างกาย"],"video":"pak.mp4",              "category":"ร่างกาย"},
    "ฟัน":              {"emoji":"🦷","color":CAT_COLOR["ร่างกาย"],"video":"fan.mp4",              "category":"ร่างกาย"},
    "ลิ้น":             {"emoji":"👅","color":CAT_COLOR["ร่างกาย"],"video":"lin.mp4",              "category":"ร่างกาย"},
    "คอ":               {"emoji":"🧣","color":CAT_COLOR["ร่างกาย"],"video":"kho.mp4",              "category":"ร่างกาย"},
    "ไหล่":             {"emoji":"🦾","color":CAT_COLOR["ร่างกาย"],"video":"lai.mp4",              "category":"ร่างกาย"},
    "อก":               {"emoji":"💗","color":CAT_COLOR["ร่างกาย"],"video":"ok.mp4",               "category":"ร่างกาย"},
    "ท้อง":             {"emoji":"🫃","color":CAT_COLOR["ร่างกาย"],"video":"thong.mp4",            "category":"ร่างกาย"},
    "หลัง":             {"emoji":"🔙","color":CAT_COLOR["ร่างกาย"],"video":"lang_body.mp4",        "category":"ร่างกาย"},
    "สะโพก":            {"emoji":"🩲","color":CAT_COLOR["ร่างกาย"],"video":"sa_phok.mp4",          "category":"ร่างกาย"},
    "แขน":              {"emoji":"💪","color":CAT_COLOR["ร่างกาย"],"video":"khaen.mp4",            "category":"ร่างกาย"},
    "ข้อศอก":           {"emoji":"🦾","color":CAT_COLOR["ร่างกาย"],"video":"kho_sok.mp4",          "category":"ร่างกาย"},
    "ข้อมือ":           {"emoji":"⌚","color":CAT_COLOR["ร่างกาย"],"video":"kho_mue.mp4",          "category":"ร่างกาย"},
    "มือ":              {"emoji":"✋","color":CAT_COLOR["ร่างกาย"],"video":"mue.mp4",              "category":"ร่างกาย"},
    "นิ้วมือ":          {"emoji":"☝️","color":CAT_COLOR["ร่างกาย"],"video":"niu_mue.mp4",          "category":"ร่างกาย"},
    "ขา":               {"emoji":"🦵","color":CAT_COLOR["ร่างกาย"],"video":"kha.mp4",              "category":"ร่างกาย"},
    "เข่า":             {"emoji":"🦵","color":CAT_COLOR["ร่างกาย"],"video":"khao_knee.mp4",        "category":"ร่างกาย"},
    "ข้อเท้า":          {"emoji":"🦶","color":CAT_COLOR["ร่างกาย"],"video":"kho_thao.mp4",         "category":"ร่างกาย"},
    "เท้า":             {"emoji":"🦶","color":CAT_COLOR["ร่างกาย"],"video":"thao.mp4",             "category":"ร่างกาย"},
    "นิ้วเท้า":         {"emoji":"🦶","color":CAT_COLOR["ร่างกาย"],"video":"niu_thao.mp4",         "category":"ร่างกาย"},
    "หัวใจ":            {"emoji":"❤️","color":CAT_COLOR["ร่างกาย"],"video":"hua_jai.mp4",          "category":"ร่างกาย"},
    "ปอด":              {"emoji":"🫁","color":CAT_COLOR["ร่างกาย"],"video":"puot.mp4",             "category":"ร่างกาย"},
    "ตับ":              {"emoji":"🫀","color":CAT_COLOR["ร่างกาย"],"video":"tap.mp4",              "category":"ร่างกาย"},
    "ไต":               {"emoji":"🫘","color":CAT_COLOR["ร่างกาย"],"video":"tai.mp4",              "category":"ร่างกาย"},
    "กระเพาะอาหาร":          {"emoji":"🍜","color":CAT_COLOR["ร่างกาย"],"video":"krapho.mp4",           "category":"ร่างกาย"},
    "ลำไส้":            {"emoji":"〰️","color":CAT_COLOR["ร่างกาย"],"video":"lam_sai.mp4",         "category":"ร่างกาย"},
    "ผิวหนัง":          {"emoji":"🫱","color":CAT_COLOR["ร่างกาย"],"video":"phiu_nang.mp4",        "category":"ร่างกาย"},
    "กระดูก":           {"emoji":"🦴","color":CAT_COLOR["ร่างกาย"],"video":"kraduk.mp4",           "category":"ร่างกาย"},
    "กล้ามเนื้อ":       {"emoji":"💪","color":CAT_COLOR["ร่างกาย"],"video":"klam_nuea.mp4",        "category":"ร่างกาย"},
    "เส้นเลือด":        {"emoji":"🩸","color":CAT_COLOR["ร่างกาย"],"video":"sen_lueat.mp4",        "category":"ร่างกาย"},
    "สมอง":             {"emoji":"🧠","color":CAT_COLOR["ร่างกาย"],"video":"sa_mong.mp4",          "category":"ร่างกาย"},

    # ══════════════════════════════════════════════════
    # อารมณ์และการสื่อสาร
    # ══════════════════════════════════════════════════
    "ใช่":              {"emoji":"✅","color":CAT_COLOR["อารมณ์"],"video":"chai.mp4",              "category":"อารมณ์"},
    "ไม่ใช่":           {"emoji":"❌","color":CAT_COLOR["อารมณ์"],"video":"mai_chai.mp4",          "category":"อารมณ์"},
    "โอเค":             {"emoji":"👌","color":CAT_COLOR["อารมณ์"],"video":"o_khe.mp4",             "category":"อารมณ์"},
    "สบายดี":           {"emoji":"😊","color":CAT_COLOR["อารมณ์"],"video":"sa_bai_di.mp4",         "category":"อารมณ์"},
    "ไม่สบาย":          {"emoji":"😷","color":CAT_COLOR["อารมณ์"],"video":"mai_sa_bai.mp4",        "category":"อารมณ์"},
    "ดีขึ้น":           {"emoji":"📈","color":CAT_COLOR["อารมณ์"],"video":"di_khuen.mp4",          "category":"อารมณ์"},
    "แย่ลง":            {"emoji":"📉","color":CAT_COLOR["อารมณ์"],"video":"yae_long.mp4",          "category":"อารมณ์"},
    "เจ็บมาก":          {"emoji":"😫","color":CAT_COLOR["อารมณ์"],"video":"jeb_mak.mp4",           "category":"อารมณ์"},
    "เจ็บน้อย":         {"emoji":"🙂","color":CAT_COLOR["อารมณ์"],"video":"jeb_noi.mp4",           "category":"อารมณ์"},
    "กลัว":             {"emoji":"😱","color":CAT_COLOR["อารมณ์"],"video":"klua.mp4",              "category":"อารมณ์"},
    "กังวล":            {"emoji":"😟","color":CAT_COLOR["อารมณ์"],"video":"kang_won.mp4",          "category":"อารมณ์"},
    "เครียด":           {"emoji":"😤","color":CAT_COLOR["อารมณ์"],"video":"khrit.mp4",             "category":"อารมณ์"},
    "เศร้า":            {"emoji":"😢","color":CAT_COLOR["อารมณ์"],"video":"sao.mp4",               "category":"อารมณ์"},
    "เหนื่อย":          {"emoji":"😮‍💨","color":CAT_COLOR["อารมณ์"],"video":"nuaei.mp4",            "category":"อารมณ์"},
    "หิว":              {"emoji":"🍽️","color":CAT_COLOR["อารมณ์"],"video":"hiu.mp4",               "category":"อารมณ์"},
    "กระหาย":           {"emoji":"🥤","color":CAT_COLOR["อารมณ์"],"video":"kra_hai.mp4",           "category":"อารมณ์"},
    "ร้อน":             {"emoji":"🥵","color":CAT_COLOR["อารมณ์"],"video":"ron.mp4",               "category":"อารมณ์"},
    "หนาว":             {"emoji":"🥶","color":CAT_COLOR["อารมณ์"],"video":"nao.mp4",               "category":"อารมณ์"},
    "ขอบคุณ":           {"emoji":"🙏","color":CAT_COLOR["อารมณ์"],"video":"khop_khun.mp4",         "category":"อารมณ์"},
    "สวัสดี":           {"emoji":"👋","color":CAT_COLOR["อารมณ์"],"video":"sa_wat_di.mp4",         "category":"อารมณ์"},
    "ลาก่อน":           {"emoji":"👋","color":CAT_COLOR["อารมณ์"],"video":"la_kon.mp4",            "category":"อารมณ์"},
    "ขอโทษ":            {"emoji":"🙇","color":CAT_COLOR["อารมณ์"],"video":"kho_thot.mp4",          "category":"อารมณ์"},
    "ช่วยด้วย":         {"emoji":"🆘","color":CAT_COLOR["อารมณ์"],"video":"chuai_duai.mp4",        "category":"อารมณ์"},
    "พูดซ้ำ":           {"emoji":"🔁","color":CAT_COLOR["อารมณ์"],"video":"phut_sam.mp4",          "category":"อารมณ์"},
    "พูดช้าๆ":          {"emoji":"🐢","color":CAT_COLOR["อารมณ์"],"video":"phut_cha_cha.mp4",      "category":"อารมณ์"},
    "น้ำ":              {"emoji":"💧","color":CAT_COLOR["อารมณ์"],"video":"nam.mp4",               "category":"อารมณ์"},
    "อาหาร":            {"emoji":"🍱","color":CAT_COLOR["อารมณ์"],"video":"ahan.mp4",              "category":"อารมณ์"},

    # ══════════════════════════════════════════════════
    # ความปลอดภัยและฉุกเฉิน
    # ══════════════════════════════════════════════════
    "ระวัง":            {"emoji":"⚠️","color":CAT_COLOR["ฉุกเฉิน"],"video":"rawang.mp4",           "category":"ฉุกเฉิน"},
    "อันตราย":          {"emoji":"☠️","color":CAT_COLOR["ฉุกเฉิน"],"video":"an_tarai.mp4",          "category":"ฉุกเฉิน"},
    "ฉุกเฉิน":          {"emoji":"🚨","color":CAT_COLOR["ฉุกเฉิน"],"video":"chuk_choen.mp4",        "category":"ฉุกเฉิน"},
    "โทร":              {"emoji":"📞","color":CAT_COLOR["ฉุกเฉิน"],"video":"tho.mp4",               "category":"ฉุกเฉิน"},
    "รถพยาบาล":         {"emoji":"🚑","color":CAT_COLOR["ฉุกเฉิน"],"video":"rot_payaban.mp4",       "category":"ฉุกเฉิน"},
    "ขอความช่วยเหลือ":  {"emoji":"🆘","color":CAT_COLOR["ฉุกเฉิน"],"video":"kho_chuai_luea.mp4",   "category":"ฉุกเฉิน"},
    "หกล้ม":            {"emoji":"🤸","color":CAT_COLOR["ฉุกเฉิน"],"video":"hok_lom.mp4",           "category":"ฉุกเฉิน"},
    "ไฟไหม้":           {"emoji":"🔥","color":CAT_COLOR["ฉุกเฉิน"],"video":"fai_mai.mp4",           "category":"ฉุกเฉิน"},
    "แพ้ยา":            {"emoji":"💊","color":CAT_COLOR["ฉุกเฉิน"],"video":"phae_ya.mp4",           "category":"ฉุกเฉิน"},
    "แพ้อาหาร":         {"emoji":"🍽️","color":CAT_COLOR["ฉุกเฉิน"],"video":"phae_ahan.mp4",         "category":"ฉุกเฉิน"},
    "หายใจไม่ออก":      {"emoji":"😮‍💨","color":CAT_COLOR["ฉุกเฉิน"],"video":"hai_jai_mai_ok.mp4",  "category":"ฉุกเฉิน"},
    "หัวใจหยุดเต้น":    {"emoji":"💔","color":CAT_COLOR["ฉุกเฉิน"],"video":"hua_jai_yut_ten.mp4",  "category":"ฉุกเฉิน"},
    "CPR":              {"emoji":"🫀","color":CAT_COLOR["ฉุกเฉิน"],"video":"CPR.mp4",               "category":"ฉุกเฉิน"},
    "เครื่องช็อตหัวใจ": {"emoji":"⚡","color":CAT_COLOR["ฉุกเฉิน"],"video":"khrueng_chot_hua_jai.mp4","category":"ฉุกเฉิน"},
    "ออกซิเจน":         {"emoji":"💨","color":CAT_COLOR["ฉุกเฉิน"],"video":"ok_si_jen.mp4",         "category":"ฉุกเฉิน"},
    "เลือดออกไม่หยุด":  {"emoji":"🩸","color":CAT_COLOR["ฉุกเฉิน"],"video":"lueat_ok_mai_yut.mp4", "category":"ฉุกเฉิน"},

    # ══════════════════════════════════════════════════
    # ตัวเลข 0–30 + คำนำหน้า (ช่อง, ห้อง, นาที, ครั้ง ฯลฯ)
    # ══════════════════════════════════════════════════
    # ── หลักหน่วย 0–9 ──────────────────────────────────
    "0":   {"emoji":"0️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_0.mp4",  "category":"ตัวเลข"},
    "1":   {"emoji":"1️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_1.mp4",  "category":"ตัวเลข"},
    "2":   {"emoji":"2️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_2.mp4",  "category":"ตัวเลข"},
    "3":   {"emoji":"3️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_3.mp4",  "category":"ตัวเลข"},
    "4":   {"emoji":"4️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_4.mp4",  "category":"ตัวเลข"},
    "5":   {"emoji":"5️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_5.mp4",  "category":"ตัวเลข"},
    "6":   {"emoji":"6️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_6.mp4",  "category":"ตัวเลข"},
    "7":   {"emoji":"7️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_7.mp4",  "category":"ตัวเลข"},
    "8":   {"emoji":"8️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_8.mp4",  "category":"ตัวเลข"},
    "9":   {"emoji":"9️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_9.mp4",  "category":"ตัวเลข"},
    # ── สองหลัก 10–30 (พบบ่อยในโรงพยาบาล) ────────────
    "10":  {"emoji":"🔟","color":CAT_COLOR["ตัวเลข"],"video":"num_10.mp4", "category":"ตัวเลข"},
    "11":  {"emoji":"1️⃣1️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_11.mp4", "category":"ตัวเลข"},
    "12":  {"emoji":"1️⃣2️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_12.mp4", "category":"ตัวเลข"},
    "13":  {"emoji":"1️⃣3️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_13.mp4", "category":"ตัวเลข"},
    "14":  {"emoji":"1️⃣4️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_14.mp4", "category":"ตัวเลข"},
    "15":  {"emoji":"1️⃣5️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_15.mp4", "category":"ตัวเลข"},
    "16":  {"emoji":"1️⃣6️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_16.mp4", "category":"ตัวเลข"},
    "17":  {"emoji":"1️⃣7️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_17.mp4", "category":"ตัวเลข"},
    "18":  {"emoji":"1️⃣8️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_18.mp4", "category":"ตัวเลข"},
    "19":  {"emoji":"1️⃣9️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_19.mp4", "category":"ตัวเลข"},
    "20":  {"emoji":"2️⃣0️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_20.mp4", "category":"ตัวเลข"},
    "21":  {"emoji":"2️⃣1️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_21.mp4", "category":"ตัวเลข"},
    "22":  {"emoji":"2️⃣2️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_22.mp4", "category":"ตัวเลข"},
    "23":  {"emoji":"2️⃣3️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_23.mp4", "category":"ตัวเลข"},
    "24":  {"emoji":"2️⃣4️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_24.mp4", "category":"ตัวเลข"},
    "25":  {"emoji":"2️⃣5️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_25.mp4", "category":"ตัวเลข"},
    "26":  {"emoji":"2️⃣6️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_26.mp4", "category":"ตัวเลข"},
    "27":  {"emoji":"2️⃣7️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_27.mp4", "category":"ตัวเลข"},
    "28":  {"emoji":"2️⃣8️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_28.mp4", "category":"ตัวเลข"},
    "29":  {"emoji":"2️⃣9️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_29.mp4", "category":"ตัวเลข"},
    "30":  {"emoji":"3️⃣0️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_30.mp4", "category":"ตัวเลข"},
    "45":  {"emoji":"4️⃣5️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_45.mp4", "category":"ตัวเลข"},
    "60":  {"emoji":"6️⃣0️⃣","color":CAT_COLOR["ตัวเลข"],"video":"num_60.mp4", "category":"ตัวเลข"},
    "หนึ่งร้อย": {"emoji":"💯","color":CAT_COLOR["ตัวเลข"],"video":"num_100.mp4","category":"ตัวเลข"},
    # ── คำนำหน้าตัวเลขในบริบทโรงพยาบาล ───────────────
    "ช่อง":      {"emoji":"🪟","color":CAT_COLOR["ตัวเลข"],"video":"chong.mp4",     "category":"ตัวเลข"},
    "ห้อง":      {"emoji":"🚪","color":CAT_COLOR["ตัวเลข"],"video":"hong.mp4",      "category":"ตัวเลข"},
    "เบอร์":     {"emoji":"🔢","color":CAT_COLOR["ตัวเลข"],"video":"boe.mp4",       "category":"ตัวเลข"},
    "คิว":       {"emoji":"🎫","color":CAT_COLOR["ตัวเลข"],"video":"khiu.mp4",      "category":"ตัวเลข"},
    "ชั้น":      {"emoji":"🏢","color":CAT_COLOR["ตัวเลข"],"video":"chan_fl.mp4",   "category":"ตัวเลข"},
    "จ่ายเงิน":  {"emoji":"💰","color":CAT_COLOR["ตัวเลข"],"video":"jai_ngoen.mp4","category":"ตัวเลข"},
    "เอกสาร":    {"emoji":"📄","color":CAT_COLOR["ตัวเลข"],"video":"ekkasan.mp4",  "category":"ตัวเลข"},
    "บัตร":      {"emoji":"🪪","color":CAT_COLOR["ตัวเลข"],"video":"bat.mp4",      "category":"ตัวเลข"},
    "นาที":      {"emoji":"⏱️","color":CAT_COLOR["ตัวเลข"],"video":"nathi2.mp4",   "category":"ตัวเลข"},
}